config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  resources :users, only: %i(show edit update) do
    member do
      get :followings, :followers
    end
  end
  resources :follows, only: %i(create destroy)
  resources :items, only: %i(new create index show destroy) do
    resources :item_comments, only: %i(create destroy)
    resource :favorites, only: %i(create destroy)
  end
  get 'search' => 'items#search'
end

app/models/item_comment.rb
# frozen_string_literal: true

class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :comment, presence: true
end

app/controllers/item_comments_controller.rb
# frozen_string_literal: true

class ItemCommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @comment = @item.item_comments.new(item_comment_params)
    @comment.user_id = current_user.id
    @comment.save!
    render :index
  end

  def destroy
    @comment = ItemComment.find(params[:id])
    @comment.destroy!
    render :index
  end

  private

  def item_comment_params
    params.require(:item_comment).permit(:comment, :user_id, :item_id)
  end
end

app/helpers/item_comments_helper.rb
# frozen_string_literal: true

module ItemCommentsHelper
end

app/views/item_comments/_form.html.erb
<%= form_with(model: [item, item_comment], url: item_item_comments_path(item)) do |f| %>
<div class="row">
  <%= f.text_area :comment, size: "50×10" %>
  <%= f.submit "コメントする", class: "btn btn-success" %>
</div>
<% end %>

app/views/item_comments/_index.html.erb
<%= item_comments.count %>件のコメント
<a data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る...</a>
<% item_comments.first(3).each do |comment| %><!--通常3件まで表示-->
  <% unless comment.id.nil? %>
    <li class="comment-container">
      <div class="comment-box">
        <div class="comment-icon">
          <%= attachment_image_tag comment.user, :image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %><br>
          <%= comment.user.name %>
        </div>
        <div class="comment-text">
          <%= comment.comment %>
          <% if comment.user == current_user %>
            <%= link_to item_item_comment_path(comment.item_id, comment.id), method: :delete, remote: true do %>
              <i class="fas fa-trash" style="color: black;"></i>
            <% end %>
          <% end %>
          <span class="comment-date pull-right">
            <%= comment.created_at.strftime('%Y%m%d %H%M%S') %>
          </span>
        </div>
      </div>
    </li>
  <% end %>
<% end %>

<div class="collapse" id="collapseExample">
  <% item_comments.offset(2).each do |comment| %>
    <% unless comment.id.nil? %>
      <li class="comment-container">
        <div class="comment-box">
          <div class="comment-icon">
            <%= attachment_image_tag comment.user, :image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %><br>
            <%= comment.user.name %>
          </div>
          <div class="comment-text">
            <%= comment.comment %>
            <% if comment.user == current_user %>
              <%= link_to item_item_comment_path(comment.item_id, comment.id), method: :delete, remote: true do %>
                <i class="fas fa-trash" style="color: black;"></i>
              <% end %>
            <% end %>
            <span class="comment-date pull-right">
              <%= comment.created_at.strftime('%Y%m%d %H%M%S') %>
            </span>
          </div>
        </div>
      </li>
    <% end %>
  <% end %>
</div>

app/views/item_comments/index.js.erb
/* global $*/
$("#comments_area").html("<%= j(render 'index', { item_comments: @comment.item.item_comments }) %>");
$("textarea").val('')