config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  resources :users, only: %i(show edit update) do
    member do
      get :followings, :followers
    end
  end
  resources :follows, only: %i(create destroy)
  resources :items, only: %i(new create index show destroy) do
    resources :item_comments, only: %i(create destroy)
    resource :favorites, only: %i(create destroy)
  end
  get 'search' => 'items#search'
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create!(item_id: params[:item_id])
    @favorite.save!
    @item = Item.find(params[:item_id])
  end

  def destroy
    @item = Item.find(params[:item_id])
    @favorite = current_user.favorites.find_by(item_id: @item.id)
    @favorite.destroy!
  end
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/views/favorites/_like.html.erb
<div class="favo">
  <% if current_user.already_favo?(item) %>
    <%= link_to item_favorites_path(item), method: :delete, remote: true, class: "btn btn-danger" do %>
      <i class="fas fa-thumbs-up">いいねを外す</i>
    <% end %>
  <% else %>
    <%= link_to item_favorites_path(item), method: :post, remote: true, class: "btn btn-light" do %>
      <i class="fas fa-thumbs-up">いいね</i>
    <% end %>
  <% end %>
</div>

app/views/favorites/create.js.erb
$('#favorite_button_<%= @item.id %>').html("<%= j(render partial: 'favorites/like', locals: {item: @item}) %>");

app/views/favorites/destroy.js.erb
$('#favorite_button_<%= @item.id %>').html("<%= j(render partial: 'favorites/like', locals: {item: @item}) %>")