config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  resources :users, only: %i(show edit update) do
    member do
      get :followings, :followers
    end
  end
  resources :follows, only: %i(create destroy)
  resources :items, only: %i(new create index show destroy) do
    resources :item_comments, only: %i(create destroy)
    resource :favorites, only: %i(create destroy)
  end
  get 'search' => 'items#search'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true

  attachment :image
  has_many :items, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :following_follows, foreign_key: 'follower_id', class_name: 'Follow', dependent: :destroy
  has_many :followings, through: :following_follows
  has_many :follower_follows, foreign_key: 'following_id', class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :follower_follows

  def already_favo?(item)
    favorites.exists?(item_id: item.id)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def follow(other_user)
    following_follows.create!(following_id: other_user.id)
  end

  def unfollow(other_user)
    following_follows.find_by(following_id: other_user.id).destroy!
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @items = @user.items.page(params[:page]).per(3)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to current_user
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(20)
    render 'users/followings'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(20)
    render 'users/followers'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.following_follows.build) do |f| %>
  <%= f.hidden_field :following_id, value: @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.following_follows.find_by(following_id: @user.id), method: :delete) do |f| %>
  <%= f.hidden_field :following_id %>
  <%= f.submit "フォロー解除する", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">プロフィールを変更</h2>

  
  <%= form_with model: @user, local:true do |f| %>
  <div class="row">
    <div class="col-3 offset-1">
      <p>プロフィール画像</p>
    </div>
    <div class="col-3">
      <%= f.attachment_field :image %>
    </div>
  </div>
  <div class="row">
    <div class="col-3 offset-1">
      <p>ハンドルネーム</p>
    </div>
    <div class="col-3">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="col-3 offset-1">
      <p>自己紹介</p>
    </div>
    <div class="col-3">
      <%= f.text_area :introduction, size: "50×10" %>
    </div>
  </div>
  <div class="row">
    <div class="col-3 offset-4">
    <%= f.submit "保存する", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="container-md">
  <h2 class="title">フォロワー一覧</h2>
  <div class="row">
    <div class="col-8 offset-2">
    <% if @users.exists? %>
      <table class="table table-striped table-hover">
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :image, :fill, 60, 60, format:'jpeg', fallback: "no_image.jpg"%></td>
          <td class="name"><%= user.name %></td>
          <td><%= link_to "見に行く", user_path(user), class: "btn btn-outline-secondary" %></td>
        </tr>
        <% end %>
      </table>
    <% else %>
      <p class="not_exist">フォロワーはいません</p>
    <% end %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container-md">
  <h2 class="title">フォロー一覧</h2>
  <div class="row">
    <div class="col-8 offset-2">
    <% if @users.exists? %>
      <table class="table table-striped table-hover">
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :image, :fill, 60, 60, format:'jpeg', fallback: "no_image.jpg"%></td>
          <td class="name"><%= user.name %></td>
          <td><%= link_to "見に行く", user_path(user), class: "btn btn-outline-secondary" %></td>
        </tr>
        <% end %>
      </table>
    <% else %>
      <p class="not_exist">フォローしてる人はいません</p>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2 class="title">ユーザーページ</h2>

  <div class="row">
    <div class="col-lg-3">
      <%= attachment_image_tag @user, :image, :fill, 200, 200, format:'jpeg', fallback: "no_image.jpg" %>
    </div>
    <div class="col-lg-5">
      <p><strong>ハンドルネーム</strong></p>
      <div class="name"><strong><%= @user.name %></strong></div>
      <p><strong>自己紹介</strong></p>
      <div class="intro">
        <p><%= @user.introduction %></p>
      </div>
    </div>

    <% if signed_in? && @user != current_user %>
      <div id="follow_form">
        <% if current_user.following?(@user) %>
          <%= render "unfollow" %>
        <% else %>
          <%= render "follow" %>
        <% end %>
      </div>
    <% end %>


    <div class="col-2">
      <strong><%= link_to "フォロー(#{@user.followings.count})", followings_user_path(@user), class: "nav-link" %></strong>
      <strong><%= link_to "フォロワー(#{@user.followers.count})", followers_user_path(@user), class: "nav-link" %></strong>
    </div>

    <div class="col-2">
      <% if @user.id == current_user.id %>
        <%=link_to " 編集する ", edit_user_path, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-10 offset-1">
      <table>
        <% @items.each do |item| %>
        <tr>
          <td class="post_name">
          <%= link_to item_path(item) do %>
            <%= item.title %>
          <% end %>
          </td>
          <td class="post_detail">
            <%= item.detail %>
          </td>
          <td>
            <%= attachment_image_tag item, :photo, :fill, 200, 150, format:'jpeg', fallback: "no_photo.jpg" %>
          </td>
        </tr>
        <% end %>
        <%= paginate @items %>
      </table>
    </div>
  </div>
</div>