config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  resources :users, only: %i(show edit update) do
    member do
      get :followings, :followers
    end
  end
  resources :follows, only: %i(create destroy)
  resources :items, only: %i(new create index show destroy) do
    resources :item_comments, only: %i(create destroy)
    resource :favorites, only: %i(create destroy)
  end
  get 'search' => 'items#search'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'

  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  attachment :photo

  belongs_to :user
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :detail, presence: true


  def self.search(keyword)
    Item.where(['title like? OR detail like?', "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/item_comment.rb
# frozen_string_literal: true

class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :comment, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true

  attachment :image
  has_many :items, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :following_follows, foreign_key: 'follower_id', class_name: 'Follow', dependent: :destroy
  has_many :followings, through: :following_follows
  has_many :follower_follows, foreign_key: 'following_id', class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :follower_follows

  def already_favo?(item)
    favorites.exists?(item_id: item.id)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def follow(other_user)
    following_follows.create!(following_id: other_user.id)
  end

  def unfollow(other_user)
    following_follows.find_by(following_id: other_user.id).destroy!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create!(item_id: params[:item_id])
    @favorite.save!
    @item = Item.find(params[:item_id])
  end

  def destroy
    @item = Item.find(params[:item_id])
    @favorite = current_user.favorites.find_by(item_id: @item.id)
    @favorite.destroy!
  end
end

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  def create
    @user = User.find(params[:follow][:following_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url) }
      format.js
    end
  end

  def destroy
    @user = User.find(params[:follow][:following_id])
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url) }
      format.js
    end
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top; end
end

app/controllers/item_comments_controller.rb
# frozen_string_literal: true

class ItemCommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @comment = @item.item_comments.new(item_comment_params)
    @comment.user_id = current_user.id
    @comment.save!
    render :index
  end

  def destroy
    @comment = ItemComment.find(params[:id])
    @comment.destroy!
    render :index
  end

  private

  def item_comment_params
    params.require(:item_comment).permit(:comment, :user_id, :item_id)
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :authenticate_user!, except: %i(index search)

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).reverse_order
  end

  def search
    @items = Item.search(params[:keyword]).page(params[:page]).reverse_order
    @keyword = params[:keyword]

    render 'index'
  end

  def show
    @item = Item.find(params[:id])
    @comment = ItemComment.new
    @comments = @item.item_comments.order(created_at: :desc)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy!
    redirect_to user_path(current_user)
  end

  private

  def item_params
    params.require(:item).permit(:title, :detail, :photo)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @items = @user.items.page(params[:page]).per(3)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to current_user
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(20)
    render 'users/followings'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(20)
    render 'users/followers'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/helpers/follows_helper.rb
# frozen_string_literal: true

module FollowsHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
end

app/helpers/item_comments_helper.rb
# frozen_string_literal: true

module ItemCommentsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HobbyShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div>
          <div class="logo">
            <%= link_to "ほびシェア", items_path %>
          </div>
          <div class="logo-eng">
            －hobby share－
          </div>
        </div>
        <div class="search-form">
          <i class="fa fa-search"></i>
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, value: @keyword %>
            <%= f.submit "検索", class: "searchButton" %>
          <% end %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", current_user, class: "btn btn-outline-info" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿する", new_item_path, class: "btn btn-outline-success" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "トップへ戻る", root_path, class: "btn btn-outline-secondary" %>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer></footer>
  </body>
</html>

app/views/posts/new.html.erb
<h1>投稿</h1>

<div class="container">
  <div class="row">
  <%= form_with model: @post, local:true do |f| %>
    <%= f.attachment_field :photo %>
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
    <%= f.label :紹介する %>
    <%= f.text_area :detail %>

    <%= f.submit "シェアする", class: "btn btn-success" %>
  <% end %>
  </div>
</div>